[package]
name = "macro-test"
version = "0.1.0"
authors = ["Lars Kroll <lkroll@kth.se>"]
edition = "2018"
publish = false

[dependencies]
kompact = { path = "../../core/"}
#component-definition-derive = { path = "../component-definition-derive/" }
